### ISSUE TITLE
Login In Error

### ISSUE THREAD

**Issue by autumndev** [flipboxfactory/saml-idp#11]
I'm back, sorry..

We are seeing instances of this on login - but its not constant. I have tested in edge, chrome and ff and only seem to get it in ff. although others reporting in edge.

My leading theory is that as we are using the same user to test across browsers it is causing some cache issue in craft which in turn causes this to throwup everynow and then..

```TypeError
Argument 2 passed to flipbox\saml\idp\services\messages\Response::create() must be an instance of flipbox\saml\idp\records\ProviderRecord, null given, called in /var/www/taomc.org/vendor/flipboxfactory/saml-idp/src/services/messages/Response.php on line 149
```

![image](https://user-images.githubusercontent.com/547193/66191455-450d0c80-e686-11e9-8d47-ddafba8f4704.png)

**Comment by dsmrt** [comment]
Can you replicate this in a consistent manner? Somehow, it's not finding itself. My concern here is the entity id is being found consistently which is bizarre.

If you look at the `findOwn()` method here ... `plugins/saml-idp/src/services/Provider.php:23`. Maybe try adding the hard coded entity id there and see if that helps. Need to figure out if the entity id is being pulled correctly. If it's not, you may want to set it in the settings so force it to be pulled a certain way here: `/admin/saml-sp/settings`.

Here's a test that you can run. Refresh (in the browsers that are having issues) the plugin's main page here `/admin/saml-idp`. Do it over and over and see if the entity id on the right hand side changes at all.
