### ISSUE TITLE
Couldn't Install Plugin

### ISSUE THREAD

**Issue by jacobgraf** [flipboxfactory/saml-idp#12]
We try to install the plugin and all we get is a red "Couldn't Install Plugin" in the Control Panel. We checked web.log and didn't see anything suspicious.

Where do we go from here?

**SAML Identity:** v1.1.0.2
**Craft:** Pro v3.4.5

**Comment by dsmrt** [comment]
Did this happen thru the plugin store or in the plugin management screen on the cp? 
Also, similarly, Did you add it as a dependency through composer or the plugin store?

**Comment by jacobgraf** [comment]
When we install via the Plugin Store it says it's installed but under Plugins, it shows as not installed so we hit install and it throws the error. We have not touched Composer manually.

**Comment by dsmrt** [comment]
Great. I’ll take a look.

**Comment by dsmrt** [comment]
Hi @jacobgraf,

I just tested this on a fresh install (both mysql and postgres drivers) and didn't see any issues. 

It's probably best to start fresh, plugin-wise, to ensure there's no issue with existing SAML tables being problematic. See my screenshot of the tables you need to remove if they already exist.

![Screen Shot 2020-02-13 at 9 34 22 AM](https://user-images.githubusercontent.com/1995478/74458545-1a5a6e00-4e47-11ea-9749-1971d59221a6.png)

Secondly, watch the logs to see if you can see what error is popping up. You can run something like the following: 
```bash
tail -f storage/logs/web.log |grep '\[error\]'
```

**Comment by dsmrt** [comment]
Closing this issue for now. Let me know if you are still seeing issues with the installation.

**Comment by thkus** [comment]
Hey, i'm possibly running into the same issue. I have the saml-sp plugin already installed, installing the saml-idp plugin on top gives me an error:
`Base table or view already exists: 1050 Table 'saml_idp_providers' already exists`

My initial goal was to turn one Craft instance into an IDP (for other Craft instances), which itself is already connected to an IDP.
As far as i can see, that doesn't seem to be possible though because both plugins are using the same tables. Am i correct?

**Comment by dsmrt** [comment]
They share some of the same tables. The keychain table and the keychain provider link table. There might be an issue with the link table — i’ll take a look. 

The idp table that you are showing however should not be shared. Those are namespaced for the plugins. 

Let me get back to you on the link table.
