### ISSUE TITLE
Login via SP redirects to non existing UID

### ISSUE THREAD

**Issue by autumndev** [flipboxfactory/saml-idp#2]
hi,

I am trying to utalise this plugin to usth users on educate.taomc.org with staging.taomc.org.

I have hooked everythign up ok but when i am redirected to staging.taomc.org to authenticate using the url:
https://somedomain.com/sso/login/request/8561098f-6fb7-4839-b0bf-2d903d5f1c05 
it does a 302 redirect to https://somedomain.com/sso/login/request/0d095f7f-ec26-45d8-be97-9932dee670fe and this then causes an invalid IDP metadata error to occur as the UID doesnt exist.

~~The only thing im not sure on is the SP uses either SHA-1 or SHA-256 as the signature algorythm and this doesn't appear as an option in the SP > Security > Encryption settings.~~

i dont understand where the uid `0d095f7f-ec26-45d8-be97-9932dee670fe` is coming from as it doesnt exist and is not in the DB.

Any help is much appretitated.

**Comment by autumndev** [comment]
ok further looking into this and if i am logged into craft the SP site logs me in with no issues. Logout doesnt work and login doesnt work from the SP.

**Comment by dsmrt** [comment]
Hello @autumndev 👋,

Glad to see you are testing this plugin out. We are not really supporting this quite yet and is still in heavy development (until 1.0). Each release could have breaking changes.

Couple tips run `composer update flipboxfactory/saml-core` and `composer update flipboxfactory/saml-idp`. I think you can actually `composer update flipboxfactory/saml-core flipboxfactory/saml-idp` but I'm not positive.

As far your issue, I'm not sure I understand your current problem fully. To test, you should be logged out of SP when testing Idp plugin to ensure sso is working. Can you help clarify your the current issue you are seeing (make sure you are up-to-date first).

**Comment by autumndev** [comment]
Hi, thanks for the reply.

I installed the plugin today so I'm hoping it's up-to-date :)

So issue is as follows.

Logged out of SP (this happens to be docebo platform), click login it
redirects to IDP but I get the error mentioned above, it goes to the
correct login URL for the IDP, redirects with a 302, and goes to the second
URL mentioned with the uid in that URL not existing in the dB.

Second issue is that with the current SP the log out URL uses http-redirect
not http-post in the XML metadata. This I think is causing it to not find
the logout location. And throw an error as it cannot getLocation() on null.

However with all that said, if I am logged into craft IDP and then go to SP
it redirects, and logs me in as expected.

Currently had to revert my tested from earlier but looking to have a new
env setup locally to retest over the weekend. Will see if a fresh install
will work as expected. Or I will post back here with more details.

**Comment by autumndev** [comment]
Right so, according to docebosass.com i cant get a test system running with SAML 2 integrationa ctivated... 

so back to the initial issue: (i talk about docebo its the SP)

Upon sucessfully integrating everything, when i try to login to the SP i get redirected to:
www.somedomain.com/sso/login/request/8561098f-6fb7-4839-b0bf-2d903d5f1c05
with the /sso... being taken from the plugin settings in the craft admin area.

upon going to that url a 302 redirect is issued taking the browser to 
www.somedomain.com/sso/login/request/0d095f7f-ec26-45d8-be97-9932dee670fe

Now i have no idea where the uid at the end of that url is coming from but its causes the following exception:
```
Error: Class 'flipbox\saml\idp\controllers\InvalidMetadata' not found in /var/www/staging.taomc.org/vendor/flipboxfactory/saml-idp/src/controllers/LoginController.php:119
Stack trace:
#0 [internal function]: flipbox\saml\idp\controllers\LoginController->actionRequest('0d095f7f-ec26-4...')
#1 /some/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /some/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /some/site/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('request', Array)
#4 /some/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('request', Array)
#5 /some/site/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('saml-idp/login/...', Array)
#6 /some/site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('saml-idp/login/...', Array)
#7 /some/site/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /some/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /some/site/public/index.php(21): yii\base\Application->run()
#10 {main}
```

as the system log in as expected once linked and already logged into craft, when you try to logout you hit the code in `flipboxfactory/saml-core/src/services/messages/LogoutRequest.php` line 49. Here we get cannot call function getLocation() of null:

```
$logout->setDestination(
            $theirProvider->getType() === SettingsInterface::SP ?
                $theirProvider->firstSpSloService(Constants::BINDING_HTTP_POST)->getLocation() :
                $theirProvider->firstIdpSloService(Constants::BINDING_HTTP_POST)->getLocation()
        );
```

I believe this is due to the line `$theirProvider->firstSpSloService(Constants::BINDING_HTTP_POST)->getLocation()` and the special way that docebo has setup their metadata as they do not use the `BINDING_HTTP_POST` binding, instead they use `BINDING_HTTP_REDIRECT` - updating your code to the below appears to work (but you know bad code and bad to update core package)

```
$service = $theirProvider->firstSpSloService(Constants::BINDING_HTTP_POST);
        if (null === $service) {
            $service = $theirProvider->firstSpSloService(Constants::BINDING_HTTP_REDIRECT);
        }
        $logout->setDestination(
            $theirProvider->getType() === SettingsInterface::SP ?
                $service->getLocation() :
                $theirProvider->firstIdpSloService(Constants::BINDING_HTTP_POST)->getLocation()
        );
```

So after all this it redirects as expected; however it doesnt log you out of craft, thus causing it to redirect back to docebo, which in turn redirects back to craft for login, which thinks its already logged in and thus redirects back to docebo with logged in user set, meaning the user is logged back in again.. (head in a spin)

I also managed to fix this as well by hacking the code further, i added a `\Craft::$app->user->logout();` to the `flipboxfactory/saml-core/src/controllers/messages/AbstractLogoutController.php` (bad, so bad) actionRequest function, line 152. which resulted in the user being logged out of craft and redirected back to docebo -> however the first issue then kicks in as the user is redirected to the login routines and the initial issue presents itsself again. 

Some extras below:

Metadata for the docebo integration (SP):
```
<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://educate.taomc.org/lms/index.php"><md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol"><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://educate.taomc.org/lms/index.php?r=SimpleSamlApp/SimpleSamlApp/modules/saml/sp/saml2-logout.php/default-sp"/><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://educate.taomc.org/lms/index.php?r=SimpleSamlApp/SimpleSamlApp/modules/saml/sp/saml2-logout.php/default-sp"/><md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://educate.taomc.org/lms/index.php?r=SimpleSamlApp/SimpleSamlApp/modules/saml/sp/saml2-acs.php/default-sp" index="0"/><md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:browser-post" Location="https://educate.taomc.org/lms/index.php?r=SimpleSamlApp/SimpleSamlApp/modules/saml/sp/saml1-acs.php/default-sp" index="1"/><md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://educate.taomc.org/lms/index.php?r=SimpleSamlApp/SimpleSamlApp/modules/saml/sp/saml2-acs.php/default-sp" index="2"/><md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:artifact-01" Location="https://educate.taomc.org/lms/index.php?r=SimpleSamlApp/SimpleSamlApp/modules/saml/sp/saml1-acs.php/default-sp/artifact" index="3"/></md:SPSSODescriptor><md:ContactPerson contactType="technical"><md:GivenName>Administrator</md:GivenName><md:EmailAddress>tech24@docebo.com</md:EmailAddress></md:ContactPerson></md:EntityDescriptor>
```
SP bindings as per craft plugin:
![image](https://user-images.githubusercontent.com/547193/60361898-613e4500-99d7-11e9-9c6b-c4fdbdcb64f6.png)

**Comment by dsmrt** [comment]
Ok. Excuse my response here. I’m on my mobile. 

Uid is found in the providers table in the db. Craft creates a uid for most items saved to the db so i just repurposed it instead of using the auto increment id. If that error is happening, you may not be using the correct sp url. Can you check that the login path/uid is correct for the sp?

Also, it looks like you are using idp initiated sso instead of sp. is that right? I’d recommend sp initiated sso. When you use sp initiated the uid is not needed. See https://saml-idp.flipboxfactory.com/initiating-sso.html#service-provider-sp-initiated. If the 

Looks like you found the issue with logout. I try and use the post binding as much as possible cause it’s usually better supported. I can throw a patch in for that but i won’t get to it until a couple weeks. Can you create a separate issue for logout?

Let me know how the uid thing goes!

**Comment by autumndev** [comment]
ok so the plugin in craft is telling me my url is `/sso/login/request/4e3e82b1-a114-4fa0-80e3-2386da8d8398` which i go to but then I am taken to `/sso/login/request/0d095f7f-ec26-45d8-be97-9932dee670fe` the UID `0d095f7f-ec26-45d8-be97-9932dee670fe` does nto exist in the database and I cannot find it referenced in the codebase either. 

This then gives the error:
```
Error: Class 'flipbox\saml\idp\controllers\InvalidMetadata' not found in /var/www/staging.taomc.org/vendor/flipboxfactory/saml-idp/src/controllers/LoginController.php:119
Stack trace:
#0 [internal function]: flipbox\saml\idp\controllers\LoginController->actionRequest('0d095f7f-ec26-4...')
#1 /var/www/staging.taomc.org/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/staging.taomc.org/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/staging.taomc.org/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('request', Array)
#4 /var/www/staging.taomc.org/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('request', Array)
#5 /var/www/staging.taomc.org/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('saml-idp/login/...', Array)
#6 /var/www/staging.taomc.org/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('saml-idp/login/...', Array)
#7 /var/www/staging.taomc.org/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/staging.taomc.org/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/staging.taomc.org/public/index.php(21): yii\base\Application->run()
#10 {main}
```
Looking at the GET, COOKIE and SESSION params i can see the intial uid in the SESSION var (in bold):
```
$_GET = [
    'p' => 'sso/login/request/0d095f7f-ec26-45d8-be97-9932dee670fe',
];

$_COOKIE = [
    'CRAFT_CSRF_TOKEN' => 'a281eca459f1079c3eaea5f6a89051de3f8183468afc7c81862ee0e0c89a4644a:2:{i:0;s:16:"CRAFT_CSRF_TOKEN";i:1;s:40:"yyE8KLQwCBOpK6s_fpVgtBUtgrBhDTkD0NLEmEWp";}',
    'CraftSessionId' => 'jjlf3brikn24jo2si934iog6ql',
];

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [],
    '1031b8c41dfff97a311a7ac99863bdc5__returnUrl' => **'https://somedomain.com/sso/login/request/4e3e82b1-a114-4fa0-80e3-2386da8d8398',**
];
```

i am still trying to find out why it is redirecting..

**Comment by autumndev** [comment]
ok so it looks like this code in https://github.com/flipboxfactory/saml-idp/blob/3210b3616466156a0465e328c44edf2305f307ea/src/controllers/LoginController.php#L99
```
$this->redirect(
            Craft::$app->config->general->getLoginPath()
        );
```
is returning that weird UID: `string(69) "redirect url: /sso/login/request/0d095f7f-ec26-45d8-be97-9932dee670fe"`

i will see what else i can trace - hoping this isnt a config issue..

**Comment by autumndev** [comment]
ok so it looks like the absolute login path is hard coded into the general config:
```
'loginPath' => '/sso/login/request/0d095f7f-ec26-45d8-be97-9932dee670fe',
```

however i do not think we put this there.. i asked around and no one has any ideas.. is it possible the plugin is putting this there?

**Comment by dsmrt** [comment]
That is something done on the [Service Provider plugin](https://saml-sp.flipboxfactory.com/configure/login.html) side but not the IdP. The plugin doesn't edit the `general.php` config. 

If the IdP site is doing login thru ajax, that is going to give you some problems. I utilize the after login craft event for a lot on the IdP.

**Comment by autumndev** [comment]
That makes sense - we have the SP plugin installed previosuly - looks like a cross over on our part caused that issue. changing it to the correct one, /accounts/login fixes the redirect issue and all appears to be working as expected. 

I am just trying to confirm login with the SP but they are now throwing errors... Onces thats doen i'll confirm logout working as epected and PR any code changes i have made for your perusal. they may not be worth much but if it helps.

**Comment by dsmrt** [comment]
> Would it be worth the SP plugin removing the modifications to the general config?

SP Plugin doesn't make any changes, that is done manually so someone must have changed that on your side.

**Comment by autumndev** [comment]
> 
> 
> > Would it be worth the SP plugin removing the modifications to the general config?
> 
> SP Plugin doesn't make any changes, that is done manually so someone must have changed that on your side.

Agreed but this plugin still relies on this parameter being set - prob just some documentation around this to notify the user - whats the default if this param does not exist?

**Comment by autumndev** [comment]
froma  quick look the RelayState parameter shouldnt be touched (https://stackoverflow.com/questions/34350160/what-is-exactly-relaystate-parameter-used-in-sso-ex-saml) 

> But the IDP should, as the documentation says, just relay it back.

so i believe it shouldnt be base64 encoded

**Comment by dsmrt** [comment]
Looks like your last comment was placed in the wrong issue. I'm ignoring it but I copied it over to the correct issue, here: https://github.com/flipboxfactory/saml-idp/issues/4#issuecomment-508170417

**Comment by dsmrt** [comment]
> Agreed but this plugin still relies on this parameter being set - prob just some documentation around this to notify the user - whats the default if this param does not exist?

That SP plugin doesn't rely on that being set but it's recommended in the documentation so the plugin doesn't have to do any guess work: https://saml-sp.flipboxfactory.com/configure/login.html#explicit-config

We are getting into questions that doesn't really pertain to this repo. This pertains to the SP repo: https://github.com/flipboxfactory/saml-sp

Closing this issue.

**Comment by autumndev** [comment]
This plugin DOES require this param - i presume if its not set it goes to default login?:

https://github.com/flipboxfactory/saml-idp/blob/3210b3616466156a0465e328c44edf2305f307ea/src/controllers/LoginController.php#L152

What i ment was that this plugin should state its required in its documentation.

**Comment by dsmrt** [comment]
My bad, it is recommended for that to be set when using the SP plugin (not this plugin). I have documentation on this here: https://saml-sp.flipboxfactory.com/configure/login.html
