### ISSUE TITLE
Can't install plugin due to abstract function not being implemented

### ISSUE THREAD

**Issue by SayChi** [flipboxfactory/saml-idp#21]
Can't install this plugin, it seems like there is a new abstract function in the saml-core on the AbstractProvider record called getDefaultSettings, but it isn't implemented in ProviderRecord

error message:
Class flipbox\saml\idp\records\ProviderRecord contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (flipbox\saml\core\records\AbstractProvider::getDefaultSettings)

**Comment by dsmrt** [comment]
I just did a fresh install. Can you tell me what your versions are for both flipboxfactory/saml-idp and flipboxfactory/saml-core.

I'm on

**Comment by SayChi** [comment]
i don't remember which versions i had at the time, they were clean installs too, but judging by the versions on that date i must have had 1.2.4 idp too

I see a commit (99af5827e45a95843987213374976532bb51cf52) that should cover it, thanks!
