### ISSUE TITLE
SAML Logout doesnt log out of craft

### ISSUE THREAD

**Issue by autumndev** [flipboxfactory/saml-idp#3]
Hello,

as per my other issue, https://github.com/flipboxfactory/saml-idp/issues/2, SAML logout does not log the user out of the craft session. 

> I also managed to fix this as well by hacking the code further, i added a \Craft::$app->user->logout(); to the flipboxfactory/saml-core/src/controllers/messages/AbstractLogoutController.php (bad, so bad) actionRequest function, line 152. which resulted in the user being logged out of craft and redirected back to docebo

**Comment by autumndev** [comment]
added pull request for change as described above tot he SAML-core code: https://github.com/flipboxfactory/saml-core/pull/4

**Comment by dsmrt** [comment]
Closing this because I don't think that the pull request is needed. However, I did make some updates to how SLO works in general which should fix this issue. You may have to recreate (delete and create) a new provider and re-exchange metadata with the SPs.

**Comment by autumndev** [comment]
hey, We have updated the plugin and cannot logout at all. 

I can see it hitting the ```flipbox\saml\core\controllers\messages\AbstractLogoutController``` and i can see if i put a ```\Craft::dd(\Craft::$app->user->logout());``` it returns `true` but im never logged out, of either craft or this other SSO integrated platform (docebo).. 

If i refresh the craft homepage im logged in, if i logout of docebo  using their logout link, im redirected back to them, but am logged in...

is there a way to test this using a third party service? (so i can rule out the docebo platform) or is there more logging i can enable in the logut flow? Or can i hire you to take a look at it?

this is the only thing stopping us signing off on our SSO integration and I cant figure out why it wouldnt be working..

**Comment by dsmrt** [comment]
I'm wondering if you are just being logged back in? Can you send me a message here: https://www.flipboxdigital.com/contact and we'll get it worked.

**Comment by dsmrt** [comment]
Figured out the issue. Going to add the `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect` binding for SLO because some times that is all people support for some reason.

**Comment by dsmrt** [comment]
I also found an issue with the Saml2Container printing out html after the redirect was already in process which, I believe was create more issues. See https://github.com/flipboxfactory/saml-core/commit/6d9006ad680c28dc44ad9c529b4bec468ecd9b0a#diff-de26083f76ae3babbd730891e3a1da21

Released with https://github.com/flipboxfactory/saml-core/releases/tag/2.0.17

Run a `composer require flipboxfactory/saml-core` and I think you should be good to go!
