### ISSUE TITLE
Persist session from frontend login form to craft dashboard on headless install

### ISSUE THREAD

**Issue by jlaughton87** [flipboxfactory/saml-idp#33]
Hi there,

Im im using craft as a headless CMS to power a Nuxt frontend.

I have a situation where i need the user to login on the frontend and then be redirected to the SAML url. The issue is that we are unable to persist the user authentication from our frontend login form to the CMS

**More info:**

Frontend: mydomain.com

CMS install: my-craft-install.mydomain.com

**Frontend:**

My frontend login form is using axios e.g:

```
const data = {
  email,
  password
};
const response = await axios.post("myfrontend.mydomain.com/api/user/login", qs.stringify(data))
```

**SAML Redirect:**
After successful login the user will be redirected to SAML url:
`
https://my-craft-install.mydomain.com/sso/login/request/[key]`

which is where the problem arises as the users are not authorised to access it.

Any help would be greatly appreciated. 
Cheers, Jamie

**Comment by dsmrt** [comment]
I might be a little confused here but I'm wondering if you need the plugin at all? Do you need sso for this site?

Are you just using the craft headless configuration with nuxt as the frontend? So there's only 2 sites:
1. nuxt site (frontend)
2. craft site (backend)

Or are multiple?
1. craft site (for user management where all of the users are stored -- the source of truth for the other sites -- an IdP)
2. another site (or sites, craft or otherwise) that has users. These users are created and managed by the IdP (no. 1 in this list).
3. nuxtjs site(s) for the frontend for no. 2 in this list

**Comment by dsmrt** [comment]
Also, if it is the first scenario (sso isn't needed), take a look at this discussion: https://github.com/craftcms/cms/discussions/8757

**Comment by jlaughton87** [comment]
Apologies for the confusion, i will try to explain more clearly.

We already have the headless setup established and working using axios for frontend user sessions. 

The inclusion of your plugin is required for us to use craft CMS as an SAML based identity provider for [Brilliant Assessment](https://www.brilliantassessments.com/). An additional platform our client has requested.

The issue we are having to achieve this is we need to redirect our users from the frontend to a link provided by saml-idp which resides within the CMS framework. e.g 

https://my-craft-install.mydomain.com/sso/login/request/[key]

On visiting this link your plugin does its magic and redirects our user to the brilliant assessment platform where they are already authenticated.

The problem i have is that the above address is not accessible to the user if they are not logged in to the CMS and our front end authentication does not persist from the root domain to the subdomain where the CMS is installed. 

Let me know if you need anymore clarification,

Thanks for your help

**Comment by jlaughton87** [comment]
I've decided to disable headless mode for this project and create a frontend login from within the craft framework rather than on a separate url as the project needs wrapping up and i cant find a time efficient solution. 

Thanks for your thoughts on this

**Comment by dsmrt** [comment]
Sorry not to be more help. I should probably look into headless with the plugin more. There hasn’t been a lot of demand for this yet but it’d make me feel better to have a plan when people run into stuff like this.

**Comment by ericdrosas87** [comment]
@dsmrt Has this issue been resolved? I've been looking to implement this plugin for a couple of our Craft sites, but headless mode not supported would be a dealbreaker.

**Comment by dsmrt** [comment]
@ericdrosas87 What is the use case? 

You have multiple frontends and you want to manage login with craft? Might be better off using something like Auth0 or Okta.

**Comment by ericdrosas87** [comment]
@dsmrt We have two separate Craft CMS instances and two React/Next.js frontends - one for each Craft backend. We'd like to use one Craft CMS instance as an identity provider for the second Craft CMS instance, so:

Craft CMS "A", with React frontend "A"
Craft CMS "B", with React frontend "B"

We've been exploring using the GraphQL Authentication plugin which has already been implemented in Craft A and frontend A, but now we want frontend B to authenticate into Craft B using Craft A as the identity provider.

**Comment by dsmrt** [comment]
Ok. This helps.

You can use the IdP plugin with our SP plugin to achieve one set of credentials for a user on 2 different Craft instances but it might be a little bit of a pain to work with using headless mode. SAML is inherently UI based and relies on redirects for it's process. You could get everything working have the issue that this OP had. 

If the user is logged into both craft instances, I guess you could use custom actions to hit the craft sites from the front ends.

**Comment by ericdrosas87** [comment]
Could any of that be alleviated with an iFrame (pointing to Craft CMS A) in frontend B, with the token being passed to frontend B from the iFrame via `Window.postMessage()` and then managed by frontend B?

**Comment by dsmrt** [comment]
That might make things more complicated but I'm not really sure. I don't really see this as a problem this plugin needs to solve. The user will be logged in via saml with the plugins. It's the communication from the frontend site that I'm not sure about.

For example:

Craft A = idp.example.com
Craft B = sp.example.com
Frontend for Craft B = fe.sp.example.com

- fe.sp.example.com is just a static site that pulls from sp.example.com
- the user can logged in via saml using a link button to sp.example.com (using idp.example.com as the idp)
- fe.sp.example.com can call sp.example.com, via graphql or api/custom action but I'm not sure how this part works. You need user specific data from craft?

**Comment by ericdrosas87** [comment]
> I don't really see this as a problem this plugin needs to solve.
For sure, I was just running by a proposed workaround to see if with your understanding of how the SAML plugins work with Craft that this sounded reasonable/possible.

>You need user specific data from craft?
This is an interesting question, I would have thought that this would have been easy question to answer, but now that I think about it I think the user account in Craft A would be pretty hollow, in that not much user data would be stored in Craft A and the user data would just be used for authenticating, while the bulk of the user data would likely be stored in Craft B.

Hmm. I may do some quick dev work/testing to see how possible this is with our current authentication in Craft A and report back on if I think I can get the authentication working in with Craft B/Craft B's frontend.

**Comment by dsmrt** [comment]
one last thing here…

I also realized just that the idp craft instance wouldn’t need to be in headless mode. The Sp instance would.
