### ISSUE TITLE
Craft 4 Availability

### ISSUE THREAD

**Issue by aarmitage** [flipboxfactory/saml-idp#45]
Hello,

We're considering this plugin for a Craft 3 site which is obviously supported at the moment, but we don't want to cut off our upgrade path to Craft 4. Will you be adding Craft 4 support to this any time soon?

Thank you.

**Comment by dsmrt** [comment]
I'm sorry for the late response here. We totally missed this issue. We have an update going up now.

**Comment by dsmrt** [comment]
Version saml-idp 4.0 released (matches the craft version now)
