### ISSUE TITLE
saml-core issues when installing both idp and sp - critical update warning

### ISSUE THREAD

**Issue by matt-adigital** [flipboxfactory/saml-idp#47]
Hi all,

We've tried to install saml-sp and saml-idp alongside each other but there is an issue with saml-core which they both require. We have the latest version of saml-idp which is 1.3.7 and requires saml-core 3.2.8 but this is incompatible with saml-sp beyond 2.6.10 as that requires a higher version of saml-core, the latest release of 2.7.4 requires saml-core 3.4.1. Screenshots below.

For now we are stuck on saml-sp 2.6.10 as a result of the above but we have critical update warnings in the control panel because of this. Can we please have an update to saml-idp to use saml-core 3.4.1 so we can run both plugins at their latest versions without critical update warnings? Thank you.

![idp1 3 7-sp2 7 0](https://user-images.githubusercontent.com/15085874/183058994-f1e21668-d336-47ce-82a4-6178dcb320d9.png)
![idp1 3 7-sp2 7 4](https://user-images.githubusercontent.com/15085874/183059002-73e98df0-45ec-4d84-b6c4-55f73af77d6b.png)

**Comment by dsmrt** [comment]
I updated the craft 3.0 version compatible plugin version to use the latest craft 3.0 version compatible saml-core. I think that fixes your issue here. Give a shot and see if that helps. New saml-idp version for you is 1.3.8.

FYI, I just released a 4.0 version of this plugin and saml-sp for Craft 4.0.

**Comment by matt-adigital** [comment]
Thank you very much @dsmrt that works perfectly now. Cheers and thanks for the fast fix!
