### ISSUE TITLE
Error report - Cannot setup connection with Okta - Craft CMS 3 + SAML IDP v1.3.8

### ISSUE THREAD

**Issue by ArpadGBondor** [flipboxfactory/saml-idp#54]
I tried to reach out to you yesterday through the contact form on your website, but I'm not sure if it worked or not.

We are having trouble setting up SSO between our client's website and Rise.com (using Okta).

We are using Craft CMS 3 and your SAML IDP (v1.3.8) plugin.

According to Rise.com, the problem is that the <SubjectConfirmationData> tags are missing the Recipient attribute.

I've checked your code, and it seems that when we try to initiate SSO login through the "https://.../sso/login/request/..." url, which is handled by `actionRequest()` in LoginController.php, on Line 184 Saml::getInstance()->getResponse()->create() there should be an extra parameter added for the Recipient attribute to appear.

ResponseAssertion.php line 160 shows that the attribute only gets added when $authnRequest is not null.

On Line 184 of LoginController.php we do not have an incoming auth request (as far as I can tell), but we have $serviceProvider, which contains the value of Assertion Consumer Service URL that needs to be passed to the Recipient attribute.

Please let us know if you can help us to solve this issue.

**Comment by dsmrt** [comment]
👋 @ArpadGBondor 

i see your form request we can communicate through that if you’d like. 

First, i want to make sure we are using the correct plugin. 

Are you trying to use Okta to login and be the source of truth for your users/identities/credentials or would you like craft to manage login?

This plugin (saml-idp) is for when you want Craft to manage login. 

If you want Okta to manage the user login, use the [saml-sp](https://github.com/flipboxfactory/saml-sp) plugin. Here is an guide using okta: https://saml-sp.flipboxfactory.com/idps/okta.html

**Comment by ArpadGBondor** [comment]
Hi @dsmrt ,

Thank you for answering so fast, I tried multiple channels to reach you, because I don't see too much activity around this plugin, and I wasn't sure if it is still maintained.

- We use saml-idp and we already have an SSO setup working with a different service provider.
- We want Craft to be "the source of truth".
- We already have one SSO connection set up with a different site, and we also tested the setup of our identity provider on `https://samltest.id/start-idp-test/`.
- We recently added Rise as a new Service Provider, but when we get redirected to Rise's website, it shows an error message. I asked Rise to investigate, and their answer was that the `SubjectConfirmationData` tags are missing the Recipient attribute in the request they get from Craft.
- I asked if they use any plugin or custom code where they could handle this issue, but they don't have such options because they use Okta.

Based on your documentation this plugin should be able to handle SSO connection to Okta.
We paid for this plugin, we'd like to ask for some technical support to find a solution to this issue, and that's why I reached out to you.

**Comment by ArpadGBondor** [comment]
This is the message I got from Rise:
```
This is what a typical SubjectConfirmation response would look like:

![expected](https://github.com/flipboxfactory/saml-idp/assets/26146115/25fdb7d3-118c-4e47-8644-95ef6554d4ba)

This is what Helpforce is sending: 

![got](https://github.com/flipboxfactory/saml-idp/assets/26146115/c2e7b071-c502-416c-828c-414bd7160101)

If you can define the Recipient and Destination URL, both would be the same as the ACS URL.
```

**Comment by dsmrt** [comment]
Thanks for the clean and clear response! I appreciate the detail here. 

Ok cool. I haven’t seen this requirement before from other SPs but everyone is different 🤪

I’ll take a look. From what you are showing me, this should be an easy add.

**Comment by ArpadGBondor** [comment]
I did some digging, because I later noticed that Rise is also complaining about a "Destination" attribute missing.

https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf#page=19
```
If the message is signed, the Destination XML attribute in the root SAML element of the protocol
message MUST contain the URL to which the sender has instructed the user agent to deliver the
message. The recipient MUST then verify that the value matches the location at which the message has
been received.
```

Can you also add this attribute? Do you want me to ask more information about it?

**Comment by dsmrt** [comment]
Got it. I’ll look at this as well. It might take a few days for me to get to this but i’ll do my best. I’ll keep you up-to-date here

**Comment by dsmrt** [comment]
Updated to [4.0.2](https://packagist.org/packages/flipboxfactory/saml-idp#4.0.2)

Can you give this a try when you have the chance?

**Comment by ArpadGBondor** [comment]
Hi @dsmrt ,

I'm sorry, but we are not using Craft 4.

Could you please deploy the change to Craft 3 as v1.3.9?

**Comment by dsmrt** [comment]
Sorry about that, I added to [1.3.10](https://packagist.org/packages/flipboxfactory/saml-idp#1.3.10) (I didn't version 1.3.9 properly 😅)

**Comment by ArpadGBondor** [comment]
Thank you very much for the quick response.
For the next two weeks, I'm not in a position to be able to test the changes, because other projects became priority.

I'd like to kindly ask you to please keep this thread open, and I'll test the work as soon as I can.

**Comment by dsmrt** [comment]
Closing for now. Let me know if you need any more help here.
