### ISSUE TITLE
License

### ISSUE THREAD

**Issue by autumndev** [flipboxfactory/saml-idp#6]
Hi,

We have been using this on our live system for integration but are now getting liecnse key request in craft. 

We cant buy the license as there is no page for it, any ideas on sorting this? dont mind paying for it, but need to be able to pay :)

**Comment by dsmrt** [comment]
No worries, sorry about that ... I think I found the issue.

**Comment by dsmrt** [comment]
Should be fixed now. Let me know if you have any other issues.
